CREATE TABLE "MICRO_ISOLATE_EXTRACT" ("PATIENT_FK" NUMBER, "FACILITY_FK" NUMBER, "LAB_FK" NUMBER
, "TEST_FK" NUMBER, "TIME_FK" NUMBER, "PHYSICIAN_FK" NUMBER, "ABNORMAL_FLAG" VARCHAR2(2 BYTE), "ACCESSION_NO" VARCHAR2(15 BYTE), "ALERT_PANIC" VARCHAR2(1 BYTE)
, "BILLING_ACCOUNT" VARCHAR2(12 BYTE), "COLLECTION_DATE" DATE, "COLLECTION_NO" NUMBER, "COLLECTION_TIME" TIMESTAMP (6), "COLLECTION_VOLUME" NUMBER
, "COMPOUND_TEST_CODE" VARCHAR2(10 BYTE), "COND_CODE" VARCHAR2(2 BYTE), "DRAW_FREQ" VARCHAR2(2 BYTE), "FLAG" VARCHAR2(2 BYTE), "ICD9" VARCHAR2(30 BYTE)
, "LOGGING_SITE" VARCHAR2(3 BYTE), "MODALITY" VARCHAR2(72 BYTE), "OBSERVATION_DATE_TIME" DATE, "OBSERVATION_RESULT_STATUS" VARCHAR2(23 BYTE)
, "ORDERING_PHYSICIAN_NAME" VARCHAR2(220 BYTE), "ORDER_DATE" DATE, "ORDER_METHOD" VARCHAR2(5 BYTE), "ORDER_NUMBER" VARCHAR2(13 BYTE), "ORDER_SEQUENCE" VARCHAR2(10 BYTE)
, "ORDER_STATUS" VARCHAR2(2 BYTE), "ORDER_TIME" TIMESTAMP (6), "PATIENT_ALIAS" VARCHAR2(2 BYTE), "PERFORMING_LAB_ID" VARCHAR2(20 BYTE), "PROVIDER_ID" VARCHAR2(10 BYTE)
, "RECORD_TYPE" NUMBER, "REFERENCE_LAB" VARCHAR2(2 BYTE), "REFERENCE_RANGE" VARCHAR2(15 BYTE), "RELEASE_DATE" DATE, "RELEASE_TIME" TIMESTAMP (6), "REPORT_NOTES" CLOB
, "REPORT_STATUS" VARCHAR2(2 BYTE), "REQUESTED_DATE_TIME" DATE, "REQUISITION_DOB" DATE, "REQUISITION_GENDER" VARCHAR2(2 BYTE), "REQUISITION_ID" VARCHAR2(10 BYTE)
, "REQUISITION_SSN" VARCHAR2(11 BYTE), "REQUISITION_STATUS" VARCHAR2(2 BYTE), "RESULT_COMMENTS" CLOB, "RESULT_METHOD" VARCHAR2(1 BYTE), "RESULT_STATUS" VARCHAR2(2 BYTE)
, "RES_RPRT_STATUS_CHNG_DT_TIME" DATE, "ROUTE" VARCHAR2(2 BYTE), "SEQUENCE_NO" NUMBER, "SOURCE_OF_COMMENT" VARCHAR2(15 BYTE), "SPECIMEN_CODE" VARCHAR2(6 BYTE)
, "SPECIMEN_DESCRIPTION" VARCHAR2(14 BYTE), "SPECIMEN_RECEIVE_DATE" DATE, "SPECIMEN_RECEIVE_TIME" TIMESTAMP (6), "SPECIMEN_SOURCE" VARCHAR2(72 BYTE)
, "SPECIMEN_TYPE" VARCHAR2(2 BYTE), "TEST_COMMENT" CLOB, "TEXTUAL_NUMERIC_RESULT" VARCHAR2(4000 BYTE), "UNITS" VARCHAR2(15 BYTE), "VALUE_TYPE" VARCHAR2(2 BYTE)
, "WORK_TYPE" VARCHAR2(2 BYTE), "PURGE_FLAG" CHAR(1 BYTE), "CREATION_TIME" TIMESTAMP (6), "LAST_UPDATE_TIME" TIMESTAMP (6), "PATIENT_TYPE" VARCHAR2(10 BYTE)
, "REMOTE_ORDER_NUM" VARCHAR2(50 BYTE), "ORDER_OCCURRENCE_ID" VARCHAR2(100 BYTE), "EMR_ORDER_ID" VARCHAR2(100 BYTE), "EMR_TEST_CODE" VARCHAR2(100 BYTE)
, "EMR_TEST_NAME" VARCHAR2(100 BYTE), "EMR_PHYSICIAN_INFO" VARCHAR2(100 BYTE), "MCI" NUMBER, "ORDER_RECEIVE_DATE" DATE, "ORDER_RECEIVE_TIME" TIMESTAMP (6)
, "SUS_METHOD" VARCHAR2(50 BYTE), "LOINC_CODE" VARCHAR2(100 BYTE), "LOINC_NAME" VARCHAR2(500 BYTE), "RR_UPDATE_TIME" TIMESTAMP (6)) 
SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 
MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) 
TABLESPACE "DW"  LOB ("REPORT_NOTES") STORE AS BASICFILE ( 
TABLESPACE "DW" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION  NOCACHE LOGGING  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 
MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT))  
LOB ("RESULT_COMMENTS") STORE AS BASICFILE ( TABLESPACE "DW");
--------------------------------------------------------
/
  CREATE TABLE "STATERPT_OWNER"."DISTRIBUTOR" 
   (	"DISTRIBUTOR_PK" NUMBER, 
	"STATE_FK" NUMBER, 
	"CRON_EXPRESSION" VARCHAR2(100 BYTE), 
	"RUN_FREQUENCY" VARCHAR2(100 BYTE), 
	"DISTRIBUTION_TYPE" VARCHAR2(250 BYTE), 
	"GENERATOR_FK" NUMBER, 
	"DISTRIBUTION_CONTEXT" VARCHAR2(500 BYTE), 
	"STATE_TARGET" VARCHAR2(300 BYTE), 
	"STATUS" VARCHAR2(50 BYTE), 
	"CREATED_DATE" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"LAST_UPDATED_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW" ;
--------------------------------------------------------
--  DDL for Index SYS_C00235232
--------------------------------------------------------

  CREATE UNIQUE INDEX "STATERPT_OWNER"."SYS_C00235232" ON "STATERPT_OWNER"."DISTRIBUTOR" ("DISTRIBUTOR_PK") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW" ;
--------------------------------------------------------
--  Constraints for Table DISTRIBUTOR
--------------------------------------------------------

  ALTER TABLE "STATERPT_OWNER"."DISTRIBUTOR" MODIFY ("STATE_FK" NOT NULL ENABLE);
  ALTER TABLE "STATERPT_OWNER"."DISTRIBUTOR" ADD PRIMARY KEY ("DISTRIBUTOR_PK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW"  ENABLE;
  ALTER TABLE "STATERPT_OWNER"."DISTRIBUTOR" MODIFY ("DISTRIBUTOR_PK" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger DISTRIBUTOR_TRIG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "STATERPT_OWNER"."DISTRIBUTOR_TRIG" 
  BEFORE INSERT 
  ON DISTRIBUTOR
  FOR EACH ROW
   WHEN (new.DISTRIBUTOR_PK is null) DECLARE
  v_id DISTRIBUTOR.DISTRIBUTOR_PK%TYPE;
BEGIN
  SELECT DISTRIBUTOR_SEQ.nextval INTO v_id FROM DUAL;

  :new.DISTRIBUTOR_PK := v_id;
END DISTRIBUTOR_TRIG;
/
ALTER TRIGGER "STATERPT_OWNER"."DISTRIBUTOR_TRIG" ENABLE;
