--------------------------------------------------------
--  DDL for Table MICRO_ISOLATE_ORGANISM
--------------------------------------------------------

  CREATE TABLE "MICRO_ISOLATE_ORGANISM" 
   (	"MICRO_ISOLATE_ORGANISM_ID" VARCHAR2(64 BYTE), 
	"GRAM" VARCHAR2(10 BYTE), 
	"ORGANISM_NAME" VARCHAR2(400 BYTE), 
	"ACCESSION_NO" VARCHAR2(64 BYTE), 
	"REQUISITION_ID" VARCHAR2(64 BYTE), 
	"RESULT_NAME" VARCHAR2(400 BYTE), 
	"TEST_NAME" VARCHAR2(256 BYTE), 
	"TEXTUAL_NUMERIC_RESULT" VARCHAR2(4000 BYTE), 
	"ABNORMAL_FLAG" VARCHAR2(2 BYTE), 
	"LAB_FK" VARCHAR2(2 BYTE), 
	"COLLECTION_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_TIME" TIMESTAMP (6)
   );
   
/   
   SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RESULTREPOSITORY" ;
--------------------------------------------------------
--  DDL for Index MICRO_ISOLATE_ORGANISM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WH_TRACK"."MICRO_ISOLATE_ORGANISM_PK" ON "WH_TRACK"."MICRO_ISOLATE_ORGANISM" ("MICRO_ISOLATE_ORGANISM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RESULTREPOSITORY" ;
--------------------------------------------------------
--  Constraints for Table MICRO_ISOLATE_ORGANISM
--------------------------------------------------------

  ALTER TABLE "WH_TRACK"."MICRO_ISOLATE_ORGANISM" ADD CONSTRAINT "MICRO_ISOLATE_ORGANISM_PK" PRIMARY KEY ("MICRO_ISOLATE_ORGANISM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RESULTREPOSITORY"  ENABLE;
