-- HL7 Message Storage Table
CREATE TABLE HL7_MESSAGE (
    HL7_MESSAGE_PK NUMBER(19) PRIMARY KEY,
    STATE_CODE VARCHAR2(2) NOT NULL,
    REGION_CODE VARCHAR2(10) NOT NULL,
    GENERATOR_FK NUMBER(19),
    CREATION_DATE TIMESTAMP NOT NULL,
    FILE_NAME VARCHAR2(255) NOT NULL,
    MESSAGE_TYPE VARCHAR2(50) NOT NULL,
    MESSAGE_CONTENT CLOB NOT NULL,
    FILE_SIZE NUMBER(19),
    HASH_VALUE VARCHAR2(64),
    STATUS VARCHAR2(20) DEFAULT 'CREATED',
    DISTRIBUTED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(50) NOT NULL,
    LAST_UPDATED_BY VARCHAR2(50),
    CREATED_DATE TIMESTAMP NOT NULL,
    LAST_UPDATED_DATE TIMESTAMP
);

CREATE SEQUENCE HL7_MESSAGE_SEQ START WITH 1 INCREMENT BY 1;

CREATE INDEX IDX_HL7_MESSAGE_STATE ON HL7_MESSAGE(STATE_CODE);
CREATE INDEX IDX_HL7_MESSAGE_DATE ON HL7_MESSAGE(CREATION_DATE);
CREATE INDEX IDX_HL7_MESSAGE_STATUS ON HL7_MESSAGE(STATUS);

-- Script to create HL7_MESSAGE_SEQ sequence
CREATE SEQUENCE HL7_MESSAGE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Grant permissions if needed (adjust based on your database user)
 GRANT SELECT ON HL7_MESSAGE_SEQ TO staterpt_user;

-- Verify sequence was created
SELECT SEQUENCE_NAME FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'HL7_MESSAGE_SEQ';
