with temp as
(SELECT
 null as PATIENT_FK ,
 null as FACILITY_FK ,
 DLO.lab_fk as LAB_FK ,
 null as TEST_FK ,
 null as TIME_FK ,
 null as PHYSICIAN_FK ,
 R.ABNORMAL_FLAG as ABNORMAL_FLAG ,
 R.ACCESSION_NUMBER as ACCESSION_NO ,
 trunc(R.COLLECTION_DATE) as COLLECTION_DATE ,
 R.COLLECTION_date_TIME as COLLECTION_TIME ,
 R.ORDER_TEST_CODE as COMPOUND_TEST_CODE ,
 DLOD.DRAW_FREQUENCY as DRAW_FREQ ,
 DLOD.diagnosis_code as ICD9 ,
 decode(DLO.lab_fk,5,'HE',7,'HS','XX') as LOGGING_SITE ,
 DLO.MODALITY_CODE as MODALITY ,
 R.COLLECTION_DATE_TIME as OBSERVATION_DATE_TIME ,
 ORDERING_PHYSICIAN_NAME as ORDERING_PHYSICIAN_NAME ,
 DLO.LAB_ESTABLISH_DATE_TIME as ORDER_DATE ,
 R.TEST_CATEGORY as ORDER_METHOD ,
 R.REQUISITION_ID as ORDER_NUMBER ,
 DLOD.ORDER_DETAIL_STATUS as ORDER_STATUS ,
 DLOD.ORDER_EFF_DATE_TIME as ORDER_TIME ,
 R.PERFORMING_LAB as PERFORMING_LAB_ID ,
 R.REFERENCE_RANGE as REFERENCE_RANGE ,
 TRUNC(R.RELEASE_DATE_TIME) as RELEASE_DATE ,
 R.RELEASE_DATE_TIME as RELEASE_TIME ,
 DLOD.REPORT_NOTES as REPORT_NOTES ,
 DLOD.REQUESTED_DATE_TIME as REQUESTED_DATE_TIME ,
 DLO.PATIENT_DOB as REQUISITION_DOB ,
 DLO.GENDER as REQUISITION_GENDER ,
 DLO.REQUISITION_ID as REQUISITION_ID ,
 DLO.SSN as REQUISITION_SSN ,
 DLO.REQUISITION_STATUS as REQUISITION_STATUS ,
 R.RESULT_COMMENT as RESULT_COMMENTS ,
 R.RESULT_STATUS as RESULT_STATUS ,
 DLOD.RESULT_RPT_CHNG_DATE_TIME as RES_RPRT_STATUS_CHNG_DT_TIME ,
 R.RESULT_SEQUENCE as SEQUENCE_NO ,
 R.SOURCE_OF_COMMENT as SOURCE_OF_COMMENT ,
 TRUNC(DLOD.SPECIMEN_RECEIVED_DATE_TIME) as SPECIMEN_RECEIVE_DATE ,
 DLOD.SPECIMEN_RECEIVED_DATE_TIME as SPECIMEN_RECEIVE_TIME ,
      NVL (dlod.specimen_method_desc, '')
           || NVL2 (
                  dlod.specimen_source_desc,
                     NVL2 (dlod.specimen_method_desc, '/', '')
                  || dlod.specimen_source_desc,
                  '')
               AS SPECIMEN_SOURCE ,
 R.TEXTUAL_RESULT_FULL as TEXTUAL_NUMERIC_RESULT ,
 R.VALUE_TYPE as VALUE_TYPE ,
 R.CREATED_DATE as CREATION_TIME ,
 R.LAST_UPDATED_DATE as LAST_UPDATE_TIME ,
 DLO.PATIENT_TYPE as PATIENT_TYPE ,
 DLOD.REMOTE_ORDER_NUM as REMOTE_ORDER_NUM ,
 DLOD.ORDER_OCCURRENCE_ID as ORDER_OCCURRENCE_ID ,
 DLOD.EMR_ORDER_ID as EMR_ORDER_ID ,
 DLOD.EMR_PHYSICIAN_INFO as EMR_PHYSICIAN_INFO ,
 TRUNC(DLOD.REQUESTED_DATE_TIME) as ORDER_RECEIVE_DATE ,
 DLOD.REQUESTED_DATE_TIME as ORDER_RECEIVE_TIME ,
 R.OBSERVATION_METHOD as SUS_METHOD ,
 R.LOINC_CODE as LOINC_CODE ,
 R.LOINC_NAME as LOINC_NAME ,
 R.LAST_UPDATED_DATE as RR_UPDATE_TIME
FROM IH_DW.DIM_LAB_ORDER DLO
JOIN IH_DW.DIM_LAB_ORDER_DETAILS DLOD ON DLOD.REQUISITION_ID = DLO.REQUISITION_ID AND DLOD.LAB_ORDER_FK = DLO.LAB_ORDER_PK
JOIN IH_DW.RESULTS R ON DLO.REQUISITION_ID = R.REQUISITION_ID AND R.LAB_ORDER_FK = DLO.LAB_ORDER_PK AND dlod.lab_order_details_pk = r.lab_order_details_fk
Where DLOD.test_category = 'MICRO'
AND  R.collection_date >= date'2024-08-28'
AND DLOD.collection_date >= date'2024-08-28'
AND DLO.collection_date >= date'2024-08-28'
and dlo.collection_date = dlod.collection_date
and dlod.collection_date=r.collection_date
AND EXTRACT(YEAR FROM DLO.collection_date) = '2024'
AND EXTRACT(YEAR FROM DLOD.collection_date) = '2024'
AND EXTRACT(YEAR FROM R.collection_date) = '2024'
--AND         (    UPPER(R.RESULT_TEST_NAME) like UPPER('%CULTURE%')
--        OR         UPPER(R.RESULT_TEST_NAME) like UPPER('%ORGANISM%')
--        OR         UPPER(R.RESULT_TEST_NAME) like UPPER('%ISOLATE%')
        )

select count(*) from temp;