with result as
		(select 
			PATIENT_FK
			, FACILITY_FK
			, LAB_FK
			, TEST_FK
			, TIME_FK
			, PHYSICIAN_FK
			, COALESCE(ABNORMAL_FLAG, ' ')
			, ACCESSION_NO
			, COALESCE(ALERT_PANIC, ' ')
			, COALESCE(BILLING_ACCOUNT, ' ')
			, COLLECTION_DATE
			, COLLECTION_NO
			, COLLECTION_TIME
			, COLLECTION_VOLUME
			, COMPOUND_TEST_CODE
			, COALESCE(COND_CODE, ' ')
			, COALESCE(DRAW_FREQ, ' ')
			, COALESCE(FLAG, ' ')
			, COALESCE(ICD9, ' ')
			, COALESCE(LOGGING_SITE, ' ')
			, COALESCE(MODALITY, ' ')
			, OBSERVATION_DATE_TIME
			, COALESCE(OBSERVATION_RESULT_STATUS, ' ')
			, COALESCE(ORDERING_PHYSICIAN_NAME, ' ')
			, ORDER_DATE
			, COALESCE(ORDER_METHOD, ' ')
			, COALESCE(ORDER_NUMBER, ' ')
			, COALESCE(ORDER_SEQUENCE, ' ')
			, COALESCE(ORDER_STATUS, ' ')
			, ORDER_TIME
			, COALESCE(PATIENT_ALIAS, ' ')
			, COALESCE(PERFORMING_LAB_ID, ' ')
			, COALESCE(PROVIDER_ID, ' ')
			, RECORD_TYPE
			, COALESCE(REFERENCE_LAB, ' ')
			, COALESCE(REFERENCE_RANGE, ' ')
			, RELEASE_DATE
			, RELEASE_TIME
			, REPORT_NOTES
			, COALESCE(REPORT_STATUS, ' ')
			, REQUESTED_DATE_TIME
			, REQUISITION_DOB
			, COALESCE(REQUISITION_GENDER, ' ')
			, REQUISITION_ID
			, COALESCE(REQUISITION_SSN, ' ')
			, COALESCE(REQUISITION_STATUS, ' ')
			, RESULT_COMMENTS
			, COALESCE(RESULT_METHOD, ' ')
			, COALESCE(RESULT_STATUS, ' ')
			, RES_RPRT_STATUS_CHNG_DT_TIME
			, COALESCE(ROUTE, ' ')
			, SEQUENCE_NO
			, COALESCE(SOURCE_OF_COMMENT, ' ')
			, COALESCE(SPECIMEN_CODE, ' ')
			, COALESCE(SPECIMEN_DESCRIPTION, ' ')
			, SPECIMEN_RECEIVE_DATE
			, SPECIMEN_RECEIVE_TIME
			, COALESCE(SPECIMEN_SOURCE, ' ')
			, COALESCE(SPECIMEN_TYPE, ' ')
			, TEST_COMMENT
			, COALESCE(TEXTUAL_NUMERIC_RESULT, ' ')
			, COALESCE(UNITS, ' ')
			, COALESCE(VALUE_TYPE, ' ')
			, COALESCE(WORK_TYPE, ' ')
			, COALESCE(PURGE_FLAG, ' ')
			, CREATION_TIME
			, LAST_UPDATE_TIME
			, COALESCE(PATIENT_TYPE, ' ')
			, COALESCE(REMOTE_ORDER_NUM, ' ')
			, COALESCE(ORDER_OCCURRENCE_ID, ' ')
			, COALESCE(EMR_ORDER_ID, ' ')
			, COALESCE(EMR_TEST_CODE, ' ')
			, COALESCE(EMR_TEST_NAME, ' ')
			, COALESCE(EMR_PHYSICIAN_INFO, ' ')
			, MCI
			, ORDER_RECEIVE_DATE
			, ORDER_RECEIVE_TIME
			, COALESCE(SUS_METHOD, ' ')
			, COALESCE(LOINC_CODE, ' ')
			, COALESCE(LOINC_NAME, ' ')
			, RR_UPDATE_TIME 
 
		from 
			RESULT_REPUSER.FACT_RESULTS 
		where
			(
				ORDER_METHOD = 'MICRO' 
				OR TEST_FK IN ( 
					select  
						TEST_PK  
					from  
						RESULT_REPUSER.DIM_TEST  
					where  
						( 
							--test_name like '%CULTURE%' 
							--or test_name like '%ORGANISM%' 
							--or 
              test_name like '%ISOLATE%' 
						) 
				)
			)
			AND collection_date >= date'2024-08-28')
      select count(1) from result; 