-- DDL script for processed_files table
-- This table tracks processed files for stages with single-copy guarantee

-- Create the processed_files table
CREATE TABLE processed_files (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    stage_name VARCHAR2(255) NOT NULL,
    file_name VARCHAR2(255) NOT NULL,
    source_path VARCHAR2(500) NOT NULL,
    destination_path VARCHAR2(500) NOT NULL,
    processed_date TIMESTAMP NOT NULL,
    created_by VARCHAR2(128),
    CONSTRAINT pk_processed_files PRIMARY KEY (id)
);

-- Create indexes for better query performance
CREATE INDEX idx_processed_files_stage_file ON processed_files(stage_name, file_name);
CREATE INDEX idx_processed_files_stage_dest ON processed_files(stage_name, destination_path);
CREATE INDEX idx_processed_files_composite ON processed_files(stage_name, file_name, source_path, destination_path);
CREATE INDEX idx_processed_files_date ON processed_files(processed_date);

-- Add comments for documentation
COMMENT ON TABLE processed_files IS 'Tracks processed files for stages with single-copy guarantee to prevent duplicate processing';
COMMENT ON COLUMN processed_files.id IS 'Primary key - auto-generated unique identifier';
COMMENT ON COLUMN processed_files.stage_name IS 'Name of the processing stage';
COMMENT ON COLUMN processed_files.file_name IS 'Name of the processed file';
COMMENT ON COLUMN processed_files.source_path IS 'Source path where the file was found';
COMMENT ON COLUMN processed_files.destination_path IS 'Destination path where the file was copied';
COMMENT ON COLUMN processed_files.processed_date IS 'Timestamp when the file was processed';
COMMENT ON COLUMN processed_files.created_by IS 'User or system that processed the file';
