-- Create the PDF_REPORTS table
CREATE TABLE PDF_REPORTS (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FILENAME VARCHAR2(255) NOT NULL,
    REPORT_TYPE VARCHAR2(50) NOT NULL,
    REGION VARCHAR2(50),
    CONTENT_TYPE VARCHAR2(100) NOT NULL,
    FILE_SIZE NUMBER NOT NULL,
    PDF_DATA BLOB NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(100),
    DESCRIPTION VARCHAR2(500),
    PATIENT_COUNT NUMBER,
    CHECKSUM VARCHAR2(64)
);

-- Create indexes for performance optimization
CREATE INDEX idx_pdf_report_type_region ON PDF_REPORTS (REPORT_TYPE, REGION);
CREATE INDEX idx_pdf_report_created_date ON PDF_REPORTS (CREATED_DATE);
CREATE INDEX idx_pdf_report_filename ON PDF_REPORTS (FILENAME);

-- Add comments for documentation
COMMENT ON TABLE PDF_REPORTS IS 'Stores PDF report binary data with metadata for retrieval and management';
COMMENT ON COLUMN PDF_REPORTS.ID IS 'Primary key - auto-generated identity';
COMMENT ON COLUMN PDF_REPORTS.FILENAME IS 'Original filename of the PDF report';
COMMENT ON COLUMN PDF_REPORTS.REPORT_TYPE IS 'Type of report (e.g., PatientResults)';
COMMENT ON COLUMN PDF_REPORTS.REGION IS 'Region for the report (e.g., East, South)';
COMMENT ON COLUMN PDF_REPORTS.CONTENT_TYPE IS 'MIME type of the file (default: application/pdf)';
COMMENT ON COLUMN PDF_REPORTS.FILE_SIZE IS 'Size of the PDF file in bytes';
COMMENT ON COLUMN PDF_REPORTS.PDF_DATA IS 'Binary data of the PDF file';
COMMENT ON COLUMN PDF_REPORTS.CREATED_DATE IS 'Timestamp when the report was created';
COMMENT ON COLUMN PDF_REPORTS.CREATED_BY IS 'User or system that created the report';
COMMENT ON COLUMN PDF_REPORTS.DESCRIPTION IS 'Optional description of the report';
COMMENT ON COLUMN PDF_REPORTS.PATIENT_COUNT IS 'Number of patients included in the report';
COMMENT ON COLUMN PDF_REPORTS.CHECKSUM IS 'SHA-256 checksum for duplicate detection';

-- Optional: Create a sequence if you prefer explicit sequence management
-- (Not needed if using IDENTITY column as above)
-- CREATE SEQUENCE PDF_REPORTS_SEQ START WITH 1 INCREMENT BY 1;

select * from PDF_REPORTS
order by id desc;


select r.order_number,r.release_date_time,r.last_update_time from asr_process_run a
join results_sent_log r ON a.order_number = r.order_number and a.result_test_code = r.result_test_code
where a.activitydate = '18-OCT-25'
and source = 'IL';

SELECT 
    r.order_number,
    TO_CHAR(r.release_date_time, 'DD-MON-YY HH24:MI') AS release_datetime,
    r.last_update_time 
FROM asr_process_run a
JOIN results_sent_log r ON a.order_number = r.order_number 
    AND a.result_test_code = r.result_test_code
WHERE a.activitydate = DATE '2025-10-18'
    AND source = 'IL';


select * from    
(SELECT 
    r.order_number,
    TO_CHAR(r.release_date_time, 'DD-MON-YY HH24:MI') AS release_datetime,
    r.last_update_time,
    ROUND(
        EXTRACT(DAY FROM (r.last_update_time - r.release_date_time)) * 24 + 
        EXTRACT(HOUR FROM (r.last_update_time - r.release_date_time)) + 
        EXTRACT(MINUTE FROM (r.last_update_time - r.release_date_time)) / 60, 2
    ) AS hour_diff
FROM asr_process_run a
JOIN results_sent_log r ON a.order_number = r.order_number 
    AND a.result_test_code = r.result_test_code
    AND source = 'IL'
) where last_update_time > '15-OCT-25 03.48.12.306700000 PM'
order by hour_diff desc
;

SELECT 
    TO_CHAR(TRUNC(r.release_date_time), 'DD-MON-YY') AS release_date,
    r.order_number,
    TO_CHAR(r.release_date_time, 'HH24:MI') AS release_time,
    r.last_update_time,
    ROUND(
        EXTRACT(DAY FROM (r.last_update_time - r.release_date_time)) * 24 + 
        EXTRACT(HOUR FROM (r.last_update_time - r.release_date_time)) + 
        EXTRACT(MINUTE FROM (r.last_update_time - r.release_date_time)) / 60, 2
    ) AS hour_diff
FROM asr_process_run a
JOIN results_sent_log r ON a.order_number = r.order_number 
    AND a.result_test_code = r.result_test_code
    AND source = 'IL'
WHERE r.last_update_time > TIMESTAMP '2025-06-01 23:48:12.306700'
ORDER BY  hour_diff DESC;