-- Script to update the uniqueness constraint on PROCESSED_FILES table
-- First drop the existing constraint
ALTER TABLE PROCESSED_FILES DROP CONSTRAINT UK_PROCESSED_FILE;

-- Then add the new constraint that includes SOURCE_PATH
ALTER TABLE PROCESSED_FILES ADD CONSTRAINT UK_PROCESSED_FILE 
    UNIQUE (STAGE_NAME, FILE_NAME, SOURCE_PATH, DESTINATION_PATH);

-- Verify the constraint was added
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME 
FROM USER_CONSTRAINTS 
WHERE TABLE_NAME = 'PROCESSED_FILES' AND CONSTRAINT_NAME = 'UK_PROCESSED_FILE';