-- SQL Script to create FILE_TRANSFER_LOG table in STATERPT_OWNER schema
-- This script aligns with the FileTransferLog JPA entity

-- Drop sequence if it exists
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE STATERPT_OWNER.FILE_TRANSFER_LOG_SEQ';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN
         RAISE;
      END IF;
END;
/

-- Drop table if it exists
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE STATERPT_OWNER.FILE_TRANSFER_LOG CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

-- Create sequence for TRANSFER_ID
CREATE SEQUENCE STATERPT_OWNER.FILE_TRANSFER_LOG_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

-- Create FILE_TRANSFER_LOG table
CREATE TABLE STATERPT_OWNER.FILE_TRANSFER_LOG (
  TRANSFER_ID NUMBER(19) NOT NULL,
  FILE_NAME VARCHAR2(255) NOT NULL,
  SOURCE_PATH VARCHAR2(1024) NOT NULL,
  DESTINATION_PATH VARCHAR2(1024) NOT NULL,
  STATE_CODE VARCHAR2(2),
  STATUS VARCHAR2(20) NOT NULL,
  FILE_SIZE NUMBER(19),
  TRANSFER_START TIMESTAMP,
  TRANSFER_END TIMESTAMP,
  ERROR_MESSAGE VARCHAR2(4000),
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY VARCHAR2(64) NOT NULL,
  UPDATED_AT TIMESTAMP,
  UPDATED_BY VARCHAR2(64),
  CONSTRAINT FILE_TRANSFER_LOG_PK PRIMARY KEY (TRANSFER_ID)
);

-- Create index for common query patterns
CREATE INDEX IDX_FTL_STATUS ON STATERPT_OWNER.FILE_TRANSFER_LOG (STATUS);
CREATE INDEX IDX_FTL_FILE_NAME ON STATERPT_OWNER.FILE_TRANSFER_LOG (FILE_NAME);
CREATE INDEX IDX_FTL_STATE_CODE ON STATERPT_OWNER.FILE_TRANSFER_LOG (STATE_CODE);
CREATE INDEX IDX_FTL_CREATED_AT ON STATERPT_OWNER.FILE_TRANSFER_LOG (CREATED_AT);

-- Create a trigger to auto-generate TRANSFER_ID from sequence
CREATE OR REPLACE TRIGGER STATERPT_OWNER.TRG_FILE_TRANSFER_LOG_ID
BEFORE INSERT ON STATERPT_OWNER.FILE_TRANSFER_LOG
FOR EACH ROW
BEGIN
  IF :NEW.TRANSFER_ID IS NULL THEN
    SELECT STATERPT_OWNER.FILE_TRANSFER_LOG_SEQ.NEXTVAL
    INTO :NEW.TRANSFER_ID
    FROM DUAL;
  END IF;
END;
/

-- Add comments to table and columns for documentation


COMMENT ON TABLE STATERPT_OWNER.FILE_TRANSFER_LOG IS 'Records file transfer operations with timestamps and status';
COMMENT ON COLUMN STATERPT_OWNER.FILE_TRANSFER_LOG.TRANSFER_ID IS 'Primary key for file transfer log';
COMMENT ON COLUMN STATERPT_OWNER.FILE_TRANSFER_LOG.FILE_NAME IS 'Name of the transferred file';
COMMENT ON COLUMN STATERPT_OWNER.FILE_TRANSFER_LOG.SOURCE_PATH IS 'Source path of the file';
COMMENT ON COLUMN STATERPT_OWNER.FILE_TRANSFER_LOG.DESTINATION_PATH IS 'Destination path for the file';
COMMENT ON COLUMN STATERPT_OWNER.FILE_TRANSFER_LOG.STATE_CODE IS 'State code associated with the transfer';
COMMENT ON COLUMN STATERPT_OWNER.FILE_TRANSFER_LOG.STATUS IS 'Current status of the transfer (PENDING, COMPLETED, ERROR, etc.)';
COMMENT ON COLUMN STATERPT_OWNER.FILE_TRANSFER_LOG.FILE_SIZE IS 'Size of the file in bytes';
COMMENT ON COLUMN STATERPT_OWNER.FILE_TRANSFER_LOG.TRANSFER_START IS 'Timestamp when the transfer started';
COMMENT ON COLUMN STATERPT_OWNER.FILE_TRANSFER_LOG.TRANSFER_END IS 'Timestamp when the transfer completed';
COMMENT ON COLUMN STATERPT_OWNER.FILE_TRANSFER_LOG.ERROR_MESSAGE IS 'Error message if the transfer failed';
COMMENT ON COLUMN STATERPT_OWNER.FILE_TRANSFER_LOG.CREATED_AT IS 'Timestamp when the record was created';
COMMENT ON COLUMN STATERPT_OWNER.FILE_TRANSFER_LOG.CREATED_BY IS 'User who created the record';
COMMENT ON COLUMN STATERPT_OWNER.FILE_TRANSFER_LOG.UPDATED_AT IS 'Timestamp when the record was last updated';
COMMENT ON COLUMN STATERPT_OWNER.FILE_TRANSFER_LOG.UPDATED_BY IS 'User who last updated the record';

-- Grant permissions (adjust as needed based on your application's security model)
GRANT SELECT, INSERT, UPDATE, DELETE ON STATERPT_OWNER.FILE_TRANSFER_LOG TO STATERPT_USER;
GRANT SELECT ON STATERPT_OWNER.FILE_TRANSFER_LOG_SEQ TO STATERPT_USER;

-- Commit the transaction
COMMIT;



/

-- Verify table creation
SELECT table_name FROM all_tables WHERE owner = 'STATERPT_OWNER' AND table_name = 'FILE_TRANSFER_LOG';

/

select transfer_id,file_name,status,created_at,updated_at from file_transfer_log;
select * from file_transfer_log;
delete file_transfer_log;

update file_transfer_log
set status = 'C';
