 CREATE TABLE "CM_OWNER"."CLINIC_QUEST" 
   (	"CLINICID" NUMBER, 
	"PAT_QUEST_ACCT_NUMBER" VARCHAR2(10 BYTE), 
	"PAT_QUEST_ACCT_START_DATE" DATE, 
	"STAFF_QUEST_ACCT_NUMBER" VARCHAR2(10 BYTE), 
	"STAFF_ACCT_START_DATE" DATE, 
	"ENV_QUEST_ACCT_NUMBER" VARCHAR2(10 BYTE), 
	"ENV_ACCT_START_DATE" DATE, 
	"QUEST_PRIMARY_LAB_LOCATION" VARCHAR2(3 BYTE), 
	"QUEST_ENV_LAB_LOCATION" VARCHAR2(3 BYTE), 
	"SRC_UPDATED_DTM" TIMESTAMP (6), 
	"ENSBL_UPDATED_DTM" TIMESTAMP (6), 
	"CREATED_DTM" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0019856
--------------------------------------------------------

  CREATE UNIQUE INDEX "CM_OWNER"."SYS_C0019856" ON "CM_OWNER"."CLINIC_QUEST" ("CLINICID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CM" ;
--------------------------------------------------------
--  Constraints for Table CLINIC_QUEST
--------------------------------------------------------

  ALTER TABLE "CM_OWNER"."CLINIC_QUEST" MODIFY ("CREATED_DTM" NOT NULL ENABLE);
  ALTER TABLE "CM_OWNER"."CLINIC_QUEST" ADD PRIMARY KEY ("CLINICID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CM"  ENABLE;