

--------------------------------------------------------
--  DDL for Table MICRO_ORGANISM_FILTER
--------------------------------------------------------

  CREATE TABLE "STATERPT_OWNER"."MICRO_ORGANISM_FILTER" 
   (	"ORGANISM_FILTER_PK" NUMBER, 
	"ORGANISMNAME" VARCHAR2(2000 BYTE), 
	"LOINCCODE" VARCHAR2(16 BYTE), 
	"LOINCNAME" VARCHAR2(2000 BYTE), 
	"VALUETYPE" VARCHAR2(16 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW" ;
--------------------------------------------------------
--  DDL for Index UIDX_ORGNAME_TYPE
--------------------------------------------------------

  CREATE UNIQUE INDEX "STATERPT_OWNER"."UIDX_ORGNAME_TYPE" ON "STATERPT_OWNER"."MICRO_ORGANISM_FILTER" ("ORGANISMNAME", "VALUETYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW" ;
  
  select * from micro_organism_filter;
  
/

--------------------------------------------------------
--  DDL for Table SNOMED_MASTER
--------------------------------------------------------

  CREATE TABLE "STATERPT_OWNER"."SNOMED_MASTER" 
   (	"SNOMEDID" NUMBER, 
	"SNOMEDCODE" VARCHAR2(256 BYTE), 
	"PREFERREDNAME" VARCHAR2(256 BYTE), 
	"LOCALNAME" VARCHAR2(256 BYTE), 
	"LAST_UPDATED_DATE" TIMESTAMP (6), 
	"SPECIMEN_SOURCE_CODE" VARCHAR2(64 BYTE), 
	"SPECIMEN_SOURCE_DESC" VARCHAR2(64 BYTE), 
	"SNOMED_TYPE" VARCHAR2(64 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW" ;
/
drop table snomed_master;

/

select * from 

select * from snomed_master;

/

begin

Insert into SNOMED_MASTER (SNOMEDID,SNOMEDCODE,PREFERREDNAME,LOCALNAME,LAST_UPDATED_DATE,SPECIMEN_SOURCE_CODE,SPECIMEN_SOURCE_DESC,SNOMED_TYPE) values (2,'446131002','Blood specimen obtained for blood culture','60',to_timestamp('16-JUN-24 09.58.21.117411000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null);
Insert into SNOMED_MASTER (SNOMEDID,SNOMEDCODE,PREFERREDNAME,LOCALNAME,LAST_UPDATED_DATE,SPECIMEN_SOURCE_CODE,SPECIMEN_SOURCE_DESC,SNOMED_TYPE) values (3,'122586001','Peritoneal dialysis fluid specimen','70',to_timestamp('16-JUN-24 10.05.30.555859000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null);
Insert into SNOMED_MASTER (SNOMEDID,SNOMEDCODE,PREFERREDNAME,LOCALNAME,LAST_UPDATED_DATE,SPECIMEN_SOURCE_CODE,SPECIMEN_SOURCE_DESC,SNOMED_TYPE) values (4,'119339001','Stool specimen','85',to_timestamp('16-JUN-24 10.08.47.227507000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null);
Insert into SNOMED_MASTER (SNOMEDID,SNOMEDCODE,PREFERREDNAME,LOCALNAME,LAST_UPDATED_DATE,SPECIMEN_SOURCE_CODE,SPECIMEN_SOURCE_DESC,SNOMED_TYPE) values (5,'258500001','Nasopharyngeal swab','50',to_timestamp('16-JUN-24 10.11.11.111976000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null);
Insert into SNOMED_MASTER (SNOMEDID,SNOMEDCODE,PREFERREDNAME,LOCALNAME,LAST_UPDATED_DATE,SPECIMEN_SOURCE_CODE,SPECIMEN_SOURCE_DESC,SNOMED_TYPE) values (6,'119334006','Sputum specimen','56',to_timestamp('16-JUN-24 10.13.02.399516000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null);
Insert into SNOMED_MASTER (SNOMEDID,SNOMEDCODE,PREFERREDNAME,LOCALNAME,LAST_UPDATED_DATE,SPECIMEN_SOURCE_CODE,SPECIMEN_SOURCE_DESC,SNOMED_TYPE) values (7,'714007005','Enterobacter cloacae','Enterobacter cloacae',to_timestamp('16-JUN-24 10.39.54.119891000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null);
Insert into SNOMED_MASTER (SNOMEDID,SNOMEDCODE,PREFERREDNAME,LOCALNAME,LAST_UPDATED_DATE,SPECIMEN_SOURCE_CODE,SPECIMEN_SOURCE_DESC,SNOMED_TYPE) values (8,'714007005','Enterobacter cloacae','Enterobacter cloacae complex',to_timestamp('16-JUN-24 10.41.42.895532000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null);
Insert into SNOMED_MASTER (SNOMEDID,SNOMEDCODE,PREFERREDNAME,LOCALNAME,LAST_UPDATED_DATE,SPECIMEN_SOURCE_CODE,SPECIMEN_SOURCE_DESC,SNOMED_TYPE) values (9,'445069004','Peritoneal dialysis fluid specimen obtained after dialysis (specimen)','65',to_timestamp('21-JUN-24 01.37.43.703269000 AM','DD-MON-RR HH.MI.SSXFF AM'),'CATHX','PD CATHETER EXI','SPECIMEN');
Insert into SNOMED_MASTER (SNOMEDID,SNOMEDCODE,PREFERREDNAME,LOCALNAME,LAST_UPDATED_DATE,SPECIMEN_SOURCE_CODE,SPECIMEN_SOURCE_DESC,SNOMED_TYPE) values (10,'258531008','Wound Swab','65',to_timestamp('21-JUN-24 01.54.39.386166000 PM','DD-MON-RR HH.MI.SSXFF AM'),'WND','SUTURE SITE','SPECIMEN');
Insert into SNOMED_MASTER (SNOMEDID,SNOMEDCODE,PREFERREDNAME,LOCALNAME,LAST_UPDATED_DATE,SPECIMEN_SOURCE_CODE,SPECIMEN_SOURCE_DESC,SNOMED_TYPE) values (11,'258531008','Wound Swab','65',to_timestamp('21-JUN-24 01.55.44.764861000 PM','DD-MON-RR HH.MI.SSXFF AM'),'WND','Unspecified','SPECIMEN');
Insert into SNOMED_MASTER (SNOMEDID,SNOMEDCODE,PREFERREDNAME,LOCALNAME,LAST_UPDATED_DATE,SPECIMEN_SOURCE_CODE,SPECIMEN_SOURCE_DESC,SNOMED_TYPE) values (12,'258531008','Wound Swab','65',to_timestamp('21-JUN-24 01.56.33.542742000 PM','DD-MON-RR HH.MI.SSXFF AM'),'WND','Drainage','SPECIMEN');
Insert into SNOMED_MASTER (SNOMEDID,SNOMEDCODE,PREFERREDNAME,LOCALNAME,LAST_UPDATED_DATE,SPECIMEN_SOURCE_CODE,SPECIMEN_SOURCE_DESC,SNOMED_TYPE) values (13,'122880004','Urine specimen obtained by clean catch procedure (specimen)','46',to_timestamp('21-JUN-24 02.00.42.633457000 PM','DD-MON-RR HH.MI.SSXFF AM'),'UR','MIDSTREAM CLEAN','SPECIMEN');
Insert into SNOMED_MASTER (SNOMEDID,SNOMEDCODE,PREFERREDNAME,LOCALNAME,LAST_UPDATED_DATE,SPECIMEN_SOURCE_CODE,SPECIMEN_SOURCE_DESC,SNOMED_TYPE) values (1,'116395006','Escherichia coli','Escherichia coli',to_timestamp('23-APR-24 02.21.52.290776000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null);
Insert into SNOMED_MASTER (SNOMEDID,SNOMEDCODE,PREFERREDNAME,LOCALNAME,LAST_UPDATED_DATE,SPECIMEN_SOURCE_CODE,SPECIMEN_SOURCE_DESC,SNOMED_TYPE) values (14,'ug/mL','MicroGramsPerMilliLiter [Mass Concentration Units]','ug/mL',to_timestamp('08-JUL-24 02.49.48.259344000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,'UNITS');
Insert into SNOMED_MASTER (SNOMEDID,SNOMEDCODE,PREFERREDNAME,LOCALNAME,LAST_UPDATED_DATE,SPECIMEN_SOURCE_CODE,SPECIMEN_SOURCE_DESC,SNOMED_TYPE) values (15,'00000000','ERTAPENEM','ERTAPENEM',to_timestamp('11-JUL-24 02.34.36.948807000 AM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null);
Insert into SNOMED_MASTER (SNOMEDID,SNOMEDCODE,PREFERREDNAME,LOCALNAME,LAST_UPDATED_DATE,SPECIMEN_SOURCE_CODE,SPECIMEN_SOURCE_DESC,SNOMED_TYPE) values (16,'00000000','TOBROMYCIN','TOBROMYCIN',to_timestamp('11-JUL-24 04.17.22.083323000 AM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null);
Insert into SNOMED_MASTER (SNOMEDID,SNOMEDCODE,PREFERREDNAME,LOCALNAME,LAST_UPDATED_DATE,SPECIMEN_SOURCE_CODE,SPECIMEN_SOURCE_DESC,SNOMED_TYPE) values (17,'00000000','TOBRAMYCIN','TOBRAMYCIN',to_timestamp('11-JUL-24 04.22.59.203140000 AM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null);
Insert into SNOMED_MASTER (SNOMEDID,SNOMEDCODE,PREFERREDNAME,LOCALNAME,LAST_UPDATED_DATE,SPECIMEN_SOURCE_CODE,SPECIMEN_SOURCE_DESC,SNOMED_TYPE) values (18,'ug/mL','MicroGramsPerMilliLiter [Mass Concentration Units]','ug/mL',to_timestamp('11-JUL-24 02.00.06.612333000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,'UNITS');
Insert into SNOMED_MASTER (SNOMEDID,SNOMEDCODE,PREFERREDNAME,LOCALNAME,LAST_UPDATED_DATE,SPECIMEN_SOURCE_CODE,SPECIMEN_SOURCE_DESC,SNOMED_TYPE) values (19,'438911005','Serratia marcescens subspecies marcescens (organism)','Serratia marcescens',to_timestamp('11-JUL-24 02.10.22.169108000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,'ORG');
Insert into SNOMED_MASTER (SNOMEDID,SNOMEDCODE,PREFERREDNAME,LOCALNAME,LAST_UPDATED_DATE,SPECIMEN_SOURCE_CODE,SPECIMEN_SOURCE_DESC,SNOMED_TYPE) values (20,'S','Susceptible. Indicates for microbiology susceptibilities only.','S',to_timestamp('15-JUL-24 01.26.35.922732000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,'HL70078');
Insert into SNOMED_MASTER (SNOMEDID,SNOMEDCODE,PREFERREDNAME,LOCALNAME,LAST_UPDATED_DATE,SPECIMEN_SOURCE_CODE,SPECIMEN_SOURCE_DESC,SNOMED_TYPE) values (21,'R','Resistant. Indicates for microbiology susceptibilities only','R',to_timestamp('15-JUL-24 01.27.15.916566000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,'HL70078');
Insert into SNOMED_MASTER (SNOMEDID,SNOMEDCODE,PREFERREDNAME,LOCALNAME,LAST_UPDATED_DATE,SPECIMEN_SOURCE_CODE,SPECIMEN_SOURCE_DESC,SNOMED_TYPE) values (22,'I','Intermediate. Indicates for microbiology susceptibilities only.','I',to_timestamp('15-JUL-24 01.27.50.195082000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,'HL70078');


end;



/
begin

Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (64,'Klebsiella species','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (69,'Salmonella enteritica ssp diarizonae','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (70,'Salmonella enteritica ssp enteritica','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (71,'Salmonella enteritica ssp houtenae','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (72,'Salmonella enteritidis','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (80,'Burkholderia pseudomallei','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (86,'Salmonella Group A','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (89,'Salmonella Group C2','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (90,'Salmonella Group D','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (96,'Salmonella ser paratyphi C','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (97,'Salmonella species','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (98,'Salmonella typhi','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (100,'Shigella boydii','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (101,'Shigella dysenteriae','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (102,'Shigella flexneri','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (103,'Shigella sonnei','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (105,'Streptococcus pneumoniae','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (106,'Escherichia coli O157','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (107,'Streptococcus Group A','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (111,'Vancomycin Resistant Staphylococcus aureus','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (112,'Vibrio (Grimontia) hollisae','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (113,'Vibrio alginolyticus','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (115,'Vibrio cholerae','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (117,'Vibrio fluvialis','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (118,'Vibrio furnissii','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (119,'Vibrio harveyi','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (120,'Vibrio metschnikovii','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (121,'Vibrio mimicus','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (122,'Vibrio parahaemolyticus','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (123,'Vibrio species','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (125,'Yersinia enterocolitica','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (254,'AMPICILLIN/SULBACTAM','18865-6','Ampicillin+Sulbactam:Susc:Pt:Isolate:OrdQn:','DRUG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (129,'Clostridium botulinum','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (130,'Brucella abortus','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (255,'AZTREONAM','18868-0','Aztreonam:Susc:Pt:Isolate:OrdQn:','DRUG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (132,'Brucella melitensis','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (133,'Brucella neotomae','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (134,'Brucella ovis','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (135,'Brucella species','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (256,'CEFAZOLIN','76-0','Cefazolin:Susc:Pt:Isolate:OrdQn:MIC','DRUG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (137,'Campylobacter cinaedi','97513-6','Campylobacter sp:PrThr:Pt:XXX:Ord:Organism specific culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (257,'CEFEPIME','6644-9','Cefepime:Susc:Pt:Isolate:OrdQn:MIC','DRUG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (139,'Campylobacter concisus','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (258,'CEFTAZIDIME','133-9','Ceftazidime:Susc:Pt:Isolate:OrdQn:MIC','DRUG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (141,'Campylobacter curvus','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (259,'CEFTRIAXONE','141-2','Ceftriaxone:Susc:Pt:Isolate:OrdQn:MIC','DRUG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (260,'ERTAPENEM','35802-8','Ertapenem:Susc:Pt:Isolate:OrdQn:','DRUG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (144,'Campylobacter fetus ssp fetus','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (145,'Campylobacter fetus subsp venerealis','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (146,'Campylobacter gracilis','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (147,'Campylobacter hominis','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (261,'GENTAMICIN','18928-2','Gentamicin:Susc:Pt:Isolate:OrdQn:','DRUG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (149,'Campylobacter jejune','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (262,'LEVOFLOXACIN','20629-2','Levofloxacin:Susc:Pt:Isolate:OrdQn:','DRUG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (151,'Campylobacter jejune subsp jejune','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (152,'Campylobacter lari','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (263,'MEROPENEM','18943-1','Meropenem:Susc:Pt:Isolate:OrdQn:','DRUG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (154,'Campylobacter rectus','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (264,'PIPERACILLIN/TAZOBACTAM','18970-4','Piperacillin+Tazobactam:Susc:Pt:Isolate:OrdQn:','DRUG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (265,'TOBRAMYCIN','18996-9','Tobramycin:Susc:Pt:Isolate:OrdQn:','DRUG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (157,'Campylobacter sputorum ssp bubulus','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (266,'TRIMETHOPRIM/SULFA','18997-7','Trimethoprim:Susc:Pt:Isolate:OrdQn:','DRUG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (267,'CEFOTAXIME','18886-2','Cefotaxime:Susc:Pt:Isolate:OrdQn:','DRUG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (160,'Candida auris','15378-3','Fungus identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (268,'CIPROFLOXACIN','18906-8','Ciprofloxacin:Susc:Pt:Isolate:OrdQn:','DRUG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (162,'Carbapenem Resistant Klebsiella pneumoniae','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (163,'Citrobacter freundii','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (269,'CLINDAMYCIN','18908-4','Clindamycin:Susc:Pt:Isolate:OrdQn:','DRUG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (165,'Enterobacter asburiae','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (270,'ERYTHROMYCIN','18919-1','Erythromycin:Susc:Pt:Isolate:OrdQn:','DRUG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (271,'FLUCONAZOLE','18924-1','Fluconazole:Susc:Pt:Isolate:OrdQn:','DRUG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (168,'Enterobacter amnigenus 1','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (169,'Enterobacter amnigenus 2','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (170,'Enterobacter cancerogenus','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (171,'Enterobacter cloacae','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (272,'GENTAMICIN HL (HIGH LEVEL)','18928-2','Gentamicin:Susc:Pt:Isolate:OrdQn:','DRUG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (273,'LINEZOLID','29258-1','Linezolid:Susc:Pt:Isolate:OrdQn:','DRUG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (174,'Enterobacter cloacae ssp dissolvens','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (175,'Enterobacter cloacae/asburiae','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (274,'MICAFUNGIN','53812-4','Micafungin:Susc:Pt:Isolate:OrdQn:MIC','DRUG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (177,'Enterobacter gergovlae','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (275,'MOXIFLOXACIN','31039-1','Moxifloxacin:Susc:Pt:Isolate:OrdQn:','DRUG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (276,'NITROFURANTOIN','18955-5','Nitrofurantoin:Susc:Pt:Isolate:OrdQn:','DRUG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (277,'OXACILLIN','18961-3','Oxacillin:Susc:Pt:Isolate:OrdQn:','DRUG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (278,'PENICILLIN','18964-7','Penicillin:Susc:Pt:Isolate:OrdQn:','DRUG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (182,'Enterobacter nimipressuralis','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (183,'Enterobacter species','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (184,'Enterobacter taylorae','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (185,'Klebsiella (Raoultella) ornthinolytica','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (186,'Klebsiella oxytoca','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (187,'Klebsiella ozaenae','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (279,'QUINUPRISTIN/DALFOPRISTIN','23640-6','Quinupristin+Dalfopristin:Susc:Pt:Isolate:OrdQn:','DRUG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (280,'RIFAMPIN','18974-6','Rifampin:Susc:Pt:Isolate:OrdQn:','DRUG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (253,'AMPICILLIN','18864-9','Ampicillin:Susc:Pt:Isolate:OrdQn:','DRUG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (281,'STREPTOMYCIN HL (HIGH LEVEL)','18982-9','Streptomycin:Susc:Pt:Isolate:OrdQn:','DRUG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (282,'TETRACYCLINE','18993-6','Tetracycline:Susc:Pt:Isolate:OrdQn:','DRUG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (283,'VANCOMYCIN','19000-9','Vancomycin:Susc:Pt:Isolate:OrdQn:','DRUG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (284,'VORICONAZOLE','32379-0','Voriconazole:Susc:Pt:Isolate:OrdQn:','DRUG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (190,'Klebsiella rhinoscleromatis','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (252,'Ampicillin','18864-9','Ampicillin:Susc:Pt:Isolate:OrdQn','Drug');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (192,'Klebsiella terrigena','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (193,'Klebsiella trevisanii','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (194,'Proteus mirabilis','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (195,'Salmonella enteritica ssp arizonae','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (200,'Serratia marcescens','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (201,'Haemophilus ducreyi','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (202,'Corynebacterium diptheriae','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (203,'Burkholderia mallei','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (204,'Neisseria gonorrhoeae','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (205,'Haemophilus influenzae','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (206,'Listeria monocytogenes','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (208,'Neisseria meningitidis','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (209,'Bordetella pertussis','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (210,'Yersinia pestis','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (211,'Salmonella choleraesuis','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (212,'Salmonella gallinarum','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (214,'Salmonella Group B','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (215,'Salmonella Group C1','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (218,'Salmonella Group E','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (219,'Salmonella Group G','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (220,'Salmonella Group VI','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (221,'Salmonella ser paratyphi A','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (222,'Salmonella ser paratyphi B','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (226,'Salmonella typhimurium','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (231,'Shigella species','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (235,'Streptococcus pyogenes (Beta Hemolytic Streptococci Group A)','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (236,'Francisella tularensis','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (237,'Vancomycin Intermediate Staphylococcus aureus','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (241,'Vibrio carchariae','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (243,'Vibrio cincinnatiensis','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (251,'Vibrio vulnificus','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (1,'Bacillus anthracis','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (4,'Brucella canis','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (9,'Brucella suis','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (11,'Campylobacter coli','97513-6','Campylobacter sp:PrThr:Pt:XXX:Ord:Organism specific culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (13,'Campylobacter cryaerophila','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (15,'Campylobacter fennelliae','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (16,'Campylobacter fetus','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (21,'Campylobacter hyointestinalis','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (23,'Campylobacter jejune subsp doylei','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (26,'Campylobacter mucosalis','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (28,'Campylobacter showae','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (29,'Campylobacter species','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (31,'Campylobacter sputorum ssp sputorum','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (32,'Campylobacter upsaliensis','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (34,'Carbapenem Resistant Escherichia coli','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (37,'Citrobacter freundii Complex','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (39,'Enterobacter aerogenes','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (40,'Enterobacter amnigenus','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (45,'Enterobacter cloacae complex','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (46,'Enterobacter cloacae ssp cloacae','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (49,'Enterobacter dissolvens','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (51,'Enterobacter hormaechei','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (52,'Enterobacter intermedius','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (53,'Enterobacter kobei','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (54,'Enterobacter ludwigii','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (61,'Klebsiella planticola','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');
Insert into MICRO_ORGANISM_FILTER (ORGANISM_FILTER_PK,ORGANISMNAME,LOINCCODE,LOINCNAME,VALUETYPE) values (62,'Klebsiella pneumoniae','43409-2','Bacteria identified:Prid:Pt:Isolate:Nom:Culture','ORG');



end;

